#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <stdbool.h>
#include <limits.h>

typedef unsigned long u64;

typedef enum {
	       SEED_TO_SOIL,
	       SOIL_TO_FERTILIZER,
	 FERTILIZER_TO_WATER,
		  WATER_TO_LIGHT,
          LIGHT_TO_TEMPERATURE,
    TEMPERATURE_TO_HUMIDITY,
       HUMIDITY_TO_LOCATION
} map;

char* mapStartTable = 
"se\
so\
fe\
wa\
li\
te\
hu";

//defines a map between two sets, A and B, with range alpha

typedef struct {
	u64 startA;
	u64 startB;
	u64 alpha;
} mapValue;

u64* seeds;
int seedCount;

mapValue* maps[7] = {};
int mapCounts[7] = {};

void appendSeed(u64 seed) {
	//append to seed list
	if (seeds == NULL) {
		seeds = malloc(sizeof(*seeds));
		seedCount = 1;
	}
	seeds = realloc(seeds, sizeof(*seeds)*seedCount);
	seeds[seedCount - 1] = seed;
	seedCount++;
}

void appendMap(u64 startA, u64 startB, u64 alpha, map mapping) {
	if (maps[mapping] == NULL) {
		maps[mapping] = malloc(sizeof(*maps[mapping]));
		mapCounts[mapping] = 1;
	}
	maps[mapping] = realloc(maps[mapping], sizeof(*maps[mapping])*mapCounts[mapping]);
	maps[mapping][mapCounts[mapping] - 1] = (mapValue){startA, startB, alpha};
	mapCounts[mapping]++;
}

int mapSort(const void* a, const void* b) {
	mapValue arg1 = *(mapValue*)a;
	mapValue arg2 = *(mapValue*)b;
	if (arg1.startA < arg2.startA) {
		return -1;
	} else if (arg1.startA > arg2.startA) {
		return 1;
	}
	return 0;
}

u64 propagateMaps(u64 seed) {
	for (int i = 0; i < 7; i++) {
		//apply mappings to all seeds
		//printf("round %d:\n", i);
		for (int k = 0; k < mapCounts[i]; k++) {
				//we test each mapping against each seed.
			if (maps[i][k].startA <= seed && seed < (maps[i][k].startA + maps[i][k].alpha)) {
				//printf("seed %ld->", seed);
				seed = maps[i][k].startB + (seed - maps[i][k].startA);
				//printf("%ld, map: %ld->%ld, range: %ld\n", seed, maps[i][k].startA, maps[i][k].startB, maps[i][k].alpha);
				k = mapCounts[i];
			}
		}
		//printf("\n");
	}
	return seed;
}

void extractSeedsAndMaps(FILE* data) {
	rewind(data);
	char buffer[1024];
	//grab the seed data first.

	int location = 0;
	fgets(buffer, 1024, data);
	//skip until we hit the first number:
	location += strlen("seeds: ");
	//we now need to find numbers and build them up
	u64 number = 0;
	for (int j = location; j < strlen(buffer); j++) {
		if (isdigit(buffer[j])) {
			//we add a number, multiply by 10 and add another number until we hit '\n'
			number *= 10;
			number += (buffer[j] - '0');
		}
		if (buffer[j] == ' ' || buffer[j] == '\n') {
			appendSeed(number);
			number = 0;
			if (buffer[j] == '\n'){
				seedCount--; //ignore erroneous extra 0 generated by the newline alg
				break;
			}
		}
	}
	location = 0;

	for (int i = 0; i < 7; i++) { //7 mappings!
		for (;;) {
			fgets(buffer, 1024, data);
			if (buffer[0] == mapStartTable[i*2 + 0] &&
				buffer[1] == mapStartTable[i*2 + 1]) {
				//we have the mapping!
				break;
			}
		}
		//mapping is now confirmed!
		for (;;) {
			fgets(buffer, 1024, data);
			if (buffer[0] == '\n') {
				break;
			}
			u64 startA = 0;
			u64 startB = 0;
			u64 alpha = 0;
			sscanf(buffer, "%ld %ld %ld", &startB, &startA, &alpha);
			//printf("adding mapping: %ld -> %ld, range: %ld, map: %d\n", startA, startB, alpha, i);
			appendMap(startA, startB, alpha, i); //enum will convert to mappings. i hope
			if (feof(data)) break;
		}
		//we now sort the mappings by startA for processing in part 1
		//we decrement map counts, off by one error is here somewhere but i dont wanna find where it is
		mapCounts[i]--;
		qsort(maps[i], mapCounts[i], sizeof(**maps), mapSort);
	}

}

void part1(FILE* data) {
	extractSeedsAndMaps(data); //seeds and maps are now extracted, we propagate seed values
	u64 lowestSeed = LONG_MAX;
	for (int i = 0; i < seedCount; i++) {
		u64 intSeed = propagateMaps(seeds[i]);
		if (intSeed <= lowestSeed) lowestSeed = intSeed;
	}
	printf("lowest seed location: %ld\n", lowestSeed);
}



void part2(FILE* data) {
	//we're just gonna brute force the values. this is bad code.
	u64 lowestSeed = LONG_MAX;
	long count = 0;
	long numOfSeeds = 0;
	for (int i = 0; i < seedCount; i+=2) {
		numOfSeeds+=seeds[i+1];
	}
	for (int i = 0; i < seedCount; i+=2) {
		for (int j = 0; j < seeds[i+1]; j++) {
			if ((count % 1000000) == 0) {
				printf("count: %ld/%ld\n", count, numOfSeeds);
			}
			u64 intSeed = propagateMaps(seeds[i] + j);
			if (intSeed <= lowestSeed) {
				lowestSeed = intSeed;
			}
			count++;
		}
	}
	printf("lowest: %lu\n", lowestSeed);
}

int main(int argc, char** argv) {
	if (argc != 2) {
		printf("please provide a file\n");
		return -1;
	}

	FILE* data = fopen(argv[1], "r");
	if (data == NULL) {
		printf("failed to open \"%s\"\n", argv[1]);
		return -1;
	}

	part1(data);
	rewind(data);
	part2(data);
	
	fclose(data);
	return 0;
}
